### ISSUE TITLE
🪲[BUG] Pico-PIO-USB does not build with pico-sdk version 2.0

### ISSUE THREAD

**Issue by rppicomidi** [sekigon-gonnoc/Pico-PIO-USB#128]
**Describe the bug you encountered:**
Perform the following steps
1. Install the pico-sdk version 2.0.
2. Run the get_deps.py script to install the Pico-PIO-USB library in TinyUSB
3. In the `Pico-PIO-USB` directory, run `git checkout -b main origin/main` to get version 0.6.0
4. Attempt to build [this program](https://github.com/rppicomidi/usb_midi_host/tree/main/examples/C-code/usb_midi_host_pio_example)
5. Build failed.
```
usb_rx.pio.h[Ln 176, Col 29]:redefinition of 'pio_sm_set_jmp_pin'
pio.h[Ln 1450, Col 20]: previous definition of 'pio_sm_set_jmp_pin' was here
```
...

**What did you expect to happen instead?**
Build should succeed
...

**What actually happened in your case?**
Build failed.

...

**Additional information**
There are 3 issues in Pico-PIO-USB that I identified:
1. The file `usb_rx.pio.h` is auto-generated. It should not be checked in.
2. The file `usb_tx.pio.h` is auto-generated. It should not be checked in.
3. The 2.0 version of `pico-sdk` defined its own version of `pio_sm_set_jmp_pin`.

Deleting the files in 1 and 2 above and removing the function definition of `pio_sm_set_jmp_pin` from file `usb_rx.pio` fixes the problem.

Other information: The TinyUSB library in `pico-sdk` version 2.0 includes an older version
of `Pico-PIO-USB` instead of 0.6.0. 

---

**Comment by sekigon-gonnoc** [comment]
Solved by #126
